config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :products
  resources :orders

  get 'users/new'

  get 'static_pages/home'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact_us'
  
  get 'cat' => 'products#index'
  
  get 'signup' => 'users#new'
  
  
  get 'catAdmin' => 'products#catAdmin'
  
  
  get 'accInfo' => 'sessions#accInfo'
  
  get 'orders' => 'orders#index'
  
  
  get 'login'=> 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  

  root 'static_pages#home'

end

app/models/order.rb
class Order < ActiveRecord::Base
validate :order_date_cannot_be_in_the_past

    def order_date_cannot_be_in_the_past
        if start_date.present? && start_date < Date.today
            errors.add(:start_date,"Can not make an order in the past")
        end
    end
end 

app/models/product.rb
class Product < ActiveRecord::Base
    def self.search(search)
        where("product_type LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  #relationship between User and Bookings, an user can have many bookings
  has_many :orders
  #This part of code will vidate the information, email and password
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX},
        uniqueness: true, case_sensitive: false
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def welcome
    render text: "Site not available at the moment"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:email, :bike, :num, :start_date, :days, :contactNum, :user_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
     if params[:search]
      @products  = Product.search(params[:search]).order("created_at DESC")
    else
      @products  = Product.all.order("created_at DESC")
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_type, :description, :price_product, :image_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in
      log_in user
      redirect_to user
    else
      # Display error message
      flash.now[:danger] = 'Invalid email Id / Password'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  
  def accInfo
    redirect_to current_user
  end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact_us
  end
  
  def phoenixAdmin
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def index
    @user = User.all
  end


  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Rent A Bike in Dublin"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in a user
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns current user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Check if user logged in
  def logged_in?
    !current_user.nil?
  end
  
  # Log user out
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
     
      <nav class="col-md-8 col-md-offset-5">
     
         <ul class="nav navbar-nav navbar-centre" >
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Catalogue", cat_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Rent a Bike", orders_path %></li>
            <li><%= link_to "User Account", accInfo_path %></li>
            <li><%= link_to "Logout", logout_path, method: "delete" %></li>
            <% else %>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "About", about_path %></li>
           <li><%= link_to "What's on in Dublin?",'http://www.visitdublin.com/whats-on' %></li>
            <li><%= link_to "Contact", contact_path %></li>
          <% end %>
        </ul>
      </nav>
     <center>
      <div class="page-header">
</center>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Rent a bike in Dublin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  </head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    
<body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

<style>
table, th, td {
    border: 3px black solid;
    border-collapse: collapse;
}
</style>
</head>
<body>

<table style="width:100%">
  <tr>

  <div class="row">
  <div class="col-md-6 col-md-offset-3">
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :bike_id %><br>
    <%= f.number_field :bike_id,class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email,class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date,class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :days %><br>
    <%= f.number_field :days,class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Bike</th>
      <th>Email</th>
      <th>Start date</th>
      <th>Days</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user_id %></td>
        <td><%= order.bike_id %></td>
        <td><%= order.email %></td>
        <td><%= order.start_date %></td>
        <td><%= order.days %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<p>
  <strong>Bike:</strong>
  <%= @order.bike_id %>
</p>



<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @order.start_date %>
</p>

<p>
  <strong>Days:</strong>
  <%= @order.days %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
  <div class="col-md-6 col-md-offset-3">
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.text_field :product_type , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :price_product %><br>
    <%= f.text_field :price_product, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing  a Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products Catalog</h1>

<head>
<style>
table, th, td {
    border: none;
    border-collapse: collapse;
}

</style>
</head>
<body>

<table style="width:100%">
  <div align="center"></div>
  <th  style="width:25%">
          <%= form_tag(products_path, :method=> "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search items", :style => "width: 205px" %>
          </br>
					 <%= image_submit_tag("button_search.png", :style => "height: 40px", :style =>"width: 105px")%>
          <% end %>
  </th>
  </div>
</table>
<br>
<table style="width:100%">

  <tr>
      <th>Type</th>
      <th>Description</th>
      <th>Price product</th>
     
      
      <th colspan="3"></th>
      
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_type %></td>
        <td><%= product.description %></td>
        <td><%= product.price_product %></td>
        <td><%= link_to image_tag("button_show.png", :style => "height: 40px", :style =>"width: 80px"), product %></td>
        <td><%= link_to image_tag("button_edit.png", :style => "height: 40px", :style =>"width: 80px"), edit_product_path(product) %></td>
        <td><%= link_to image_tag("button_destroy.png", :style => "height: 40px", :style =>"width: 80px"), product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>
<br>
<br>
<table style="width:100%">
<%= link_to  image_tag("button_create-product.png", :style => "height: 40px", :style =>"width: 190px"), new_product_path %>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product_Type:</strong>
  <%= @product.product_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price product:</strong>
  <%= @product.price_product %>
</p>

<p>
 
  <%=image_tag( @product.image_url , :style => "height: 150px") %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %> |
<%= link_to 'Add to Cart', orders_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanations">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "errors") %>
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>
     
		  <h1>About Us</h1>
		  <p class="text-center"> <strong> Rent a Bike in Dublin </strong></p>
		  <br>
		  <div class="row">
			  <div class="col-md-6">
				  <div class="block block-icon-left">
					  <div class="icon-content">
						  <h3>Our Location</h3>
						  <p>The shop is located in Sandymount Village - South Side Dublin  </p>
                          <p>Our main GOAL is to give you the bike that best suit you at lowest price</p>
                          <p>We are passionate about cycling, we provide our service all around Dublin and
                          offering extras gadgets such as helmet, GPS, Locks and even picnic baskets *upon request*</p>
                          <p>We provide a huge range of bikes:  Kids| Standard|Tandems|Heritage|</p>
                          		<strong>Come to visit Us, here is where we are:</strong>
                          <%= link_to image_tag("sandymount.png",:style => "height: 200px", alt: "cycling_sandymount2"), 'https://www.google.ie/maps/search/sandymount/@53.2994557,-6.2086879,15z?hl=es' %>
					  </div>
				  </div>
			  </div>
			  <div class="col-md-6">
				  <div class="block block-icon-left">
					  <div class="icon-content">
						  <h3>Services</h3>
						  <p>Our GPS service will help navigate you on your adventures around Dublin</p>
                          <p>Our team  make sure all bikes are service checked and tested before each rental </p>
                          <p class="text-center"><strong>" Because we would love to see you fully addicted to cycling just like us"
                          						Follow us on </strong></p>
                          
                          	
							 <a href="https://facebook.com/login/"><%= image_tag "facebook.png"%></a><br/>
							 
							<a href="https://twitter.com/login/"><%= image_tag "twitter.png"%></a><br/>
							
							<a href="https://www.instagram.com"><%= image_tag "Insta.png"%></a><br/>
							
						
						</div>
					  </div>
				  </div>
			  </div>
			  </div>
			  

app/views/static_pages/contact_us.html.erb
<% provide(:title, "Contact Us") %>



<h1>Contact Us</h1>

<table align="center">
<div class="itemBody">  											
	<div class="itemFullText">
		<h4>Opening Times</h4>
			<p>Mondays to  Fridays   9am-7pm<br>
			  Saturday & Sundays    10am-5pm </p>
		<h4>Contact Details </h4>
		<p><strong>Address:</strong>  Jessica's bike shop Sandymount Village, Co Dublin </p>
		<p><strong>Telephone:</strong> 353 01 7882574 </p>
		
</table>		
	
	
		<h3 style="text-align: center"> Contact Form</h3>
		<div class="row">
  		<div class="col-md-6 col-md-offset-3">
	<form onsubmit="javascript:alert('Thank you for your Comment');return false;" method="post"  id="userForm" enctype="multipart/form-data" action=""><fieldset class="formFieldset">

<!-- Do not remove this ID, it is used to identify the page so that the pagination script can work correctly -->

  
	
		<div class="formCaption">Full Name<strong class="formRequired">: *</strong></div>
		<div class="formBody"><input type="text" value="" size="25"  name="form[fullname]" id="fullnamename"  class="form-control"/></div>
		<div class="formDescription"></div>


		<div class="formCaption">Email <strong class="formRequired">: *</strong></div>
		<div class="formBody"><input type="text" value="" size="25"  name="form[Email]" id="Email"  class="form-control"/></div>
		<div class="formDescription"></div>

	
		<div class="formCaption">Phone<strong class="formRequired">:</strong></div>
		<div class="formBody"><input type="text" value="" size="20"  name="form[Phone]" id="Phone"  class="form-control"/></div>
		<div class="formDescription"></div>

	
		<div class="formCaption">Message:</div>
		<div class="formBody" style="margin-top:10px;"><textarea cols="55" rows="8" name="form[message]" id="message"  class="form-control"></textarea></div>
		<div class="formDescription"></div>


		<div class="formCaption"></div>
		<div class="formBody"><input type="submit" value="Submit"  Full name="form[Submit]" id="Submit" class="btn btn-primary" /><span class="formClr"></span></div>
		<div class="formDescription"></div>
	

</fieldset>
</form>
</div>
</div>
</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center">
  

<%= image_tag("logo.png")%>
</div>
  <h2>Getting around Dublin by <strong>Bike</strong> means you don't have to worry about sticking to bus timetables.</br></br>
      Whether you're just popping down to the shops to pick up some milk, commuting to work or</br></br>
      cycling to get fit and help the environment.</br></br>
      <strong>cycling gives you the freedom to be flexible and spontaneous.</strong></br></br></h2>
 
 
                <h3 class="text-center"><strong>New Here? Sign Up</strong> </br> <div align="center">
                  <%= link_to image_tag("button_signup.png", :style => "height: 40px", :style =>"width: 105px"), signup_path, class: "btn btn-success" %>

                  </div></h3>
                  
</div>

app/views/static_pages/phoenixAdmin.html.erb
<% provide(:title, "Administration") %>

<div class="page-header">

<h1>Administrator Functions</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Rent a Bike in Dublin - Administration</div>
  <div class="panel-body">
    <p>  Administration Functions for Rent a Bike in Dublin</p>

<table class="table">
  <tr>
      <th>Description</th>
      <th colspan="3"></th>
  </tr>
  
  </div>
 
      <tr>
        <td><%= "Catalogue Maintenace Tasks" %></td>
        <td><%= link_to 'Access', catAdmin_path, class: 'btn btn-success' %></td>
      </tr>
      <tr>
        <td><%= "User Tasks" %></td>
        <td><%= link_to 'Access', userListing_path, class: 'btn btn-success' %></td>
      </tr>
      <tr>
        <td><%= "List Bookings" %></td>
        <td><%= link_to 'Access', phoenixList_path, class: 'btn btn-success' %></td>
      </tr>

</table>

<div class="panel-footer">
  <%= link_to 'Home', root_path, class: 'btn btn-success' %>
  </div>

  </div>

app/views/users/Index.html.erb
<div class="page-header">

<h1>User Listing</h1>

</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Dublin Rental Bikes Registered Accounts</div>
  <div class="panel-body">


<table class="table">
  <tr>
      <th>ID Number</th>
      <th>Name</th>
      <th>Email</th>
  </tr>
  
  </div>
 
    <% @user.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
  <% end %>
</table>

<div class="panel-footer">
  <%= link_to 'New user', signup_path, class: 'btn btn-success' %>
  </div>

  </div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1 class="text-center">Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Account Information</h1>
</br>
<h2>User ID: <%= @user.id %></br></br>
Username: <%= @user.name %></br></br>
Email: <%= @user.email %></br></br>
Address: <%= @user.address %></h2></br>